services:
  skill-sync-db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skill_sync_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 5

  skill-sync-app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      skill-sync-db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "localhost:host-gateway"
    # Remove the command from here - let Dockerfile handle it
    networks:
      - skill_sync_network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
        - action: sync
          path: ./prisma
          target: /usr/src/app/prisma
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./pnpm-lock.yaml

  # Remove prisma-studio from docker-compose - run it locally instead

networks:
  skill_sync_network:

volumes:
  postgres_data: